export const ACTION_TYPES = {
  SET_USER: 'SET_USER',
  SET_USER_AVATAR: 'SET_USER_AVATAR',
  SET_AUTH_LOADING: 'SET_AUTH_LOADING',
  SET_AUTH_LOGGED: 'SET_AUTH_LOGGED',
  // Tic Tac Toe Actions [ START ]
  TTT_SET_GAMES: 'TTT_SET_GAMES',
  TTT_ADD_LOBBY: 'TTT_ADD_LOBBY',
  TTT_ADD_PLAYER_TO_LOBBY: 'TTT_ADD_PLAYER_TO_LOBBY',
  TTT_REMOVE_PLAYER_FROM_LOBBY: 'TTT_REMOVE_PLAYER_FROM_LOBBY',
  TTT_DELETE_GAME: 'TTT_DELETE_GAME',
  TTT_PLAYER_TURN: 'TTT_PLAYER_TURN',
  TTT_GAME_FINISHED: 'TTT_GAME_FINISHED',
  TTT_RESET_STATE: 'TTT_RESET_STATE',
  // Tic Tac Toe Actions [  END  ]
};
