export const ACTION_TYPES = {
  SET_USER: 'SET_USER',
  SET_USER_AVATAR: 'SET_USER_AVATAR',
  SET_AUTH_LOADING: 'SET_AUTH_LOADING',
  SET_AUTH_LOGGED: 'SET_AUTH_LOGGED',
  SET_GAMES: 'SET_GAMES',
  SET_ACTIVE_GAME: 'SET_ACTIVE_GAME',
  ADD_LOBBY: 'ADD_LOBBY',
  ADD_PLAYER_TO_LOBBY: 'ADD_PLAYER_TO_LOBBY',
  REMOVE_PLAYER_FROM_LOBBY: 'REMOVE_PLAYER_FROM_LOBBY',
  DELETE_GAME: 'DELETE_GAME',
  ADD_CHAT_MESSAGE: 'ADD_CHAT_MESSAGE',
};
